"""add repositories table

Revision ID: 5f00abca5fe8
Revises: 5bdbd6373438
Create Date: 2026-06-18 23:51:16.960465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f00abca5fe8'
down_revision: Union[str, Sequence[str], None] = '5bdbd6373438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('files_ingested', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('repository_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('source_type',sa.String(length=20),nullable=False,server_default='upload'))    
    op.alter_column('documents', 'file_id',existing_type=sa.INTEGER(),nullable=True)
    op.create_foreign_key(None, 'documents', 'repositories', ['repository_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documents', 'source_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'repository_id')
    op.drop_table('repositories')
    # ### end Alembic commands ###
